(require 'init-packages)
(require 'init-better-defaults)
(require 'init-keybindings)
(require 'init-ui)
(require 'init-input)
(require 'init-evil)
(require 'init-window)
(require 'init-dev)
(require 'init-completion)
(require 'init-magit)
(require 'init-lsp)
(require 'init-tools)
(require 'init-org)
(require 'init-workspace)
(require 'init-treemacs)
(require 'init-translation)

(provide 'init)
